INIT_Y0 = 3
INIT_Y1 = 73
INIT_X0 = 3
INIT_X1 = 83
OVAL_WIDTH = 80
COL_WIDTH = 100
WIN_W = 710
TITLE_H = 60
FINT_SIZE = 30
CAN_W = 690
CAN_H = 60
FRAME_W = 700
FRAME_H = 20
FRAME_BD = 2
TK = 1
BT_W = 13
COL_W = 91
COL_H = 480
TEXT_TITLE = "Four In A Row"
TEXT_FILL = "brown4"
TITLE_BG = "grey"
FONT = "Comic Sans MS"
BOLD_FONT = "bold"
BG_COLOR = "NavajoWhite4"
U_FRAME = "black"
FILL_BOTH = "both"
WIN_WIDTH = 3
ERROR_TITLE = "ERROR!"
SERVER = "Server"
WINNER_TITLE = "We Have A winner!"
LOSER_TEXT = "You lost............"
WINNER_TEXT = "You Won!!!"
DREW_TITLE = "The game is ended"
DREW_TEXT = "It's a draw!"
BUTTONS_SIDE = "right"
COLUMNS_SIDE = "left"
TITLE_SIDE = "top"
